using System.Text;
using EngineContext.Editor.Model;

namespace EngineContext.Editor.Formatting.Sections
{
    /// <summary>섹션 1 — Header: 자동생성 고지 + meta 주석 블록 (FS §4.1). 비결정 요소는 여기에만.</summary>
    internal static class HeaderSection
    {
        public static string Render(Snapshot snapshot, FormatterLimits limits)
        {
            var meta = snapshot.meta;
            var sb = new StringBuilder();
            sb.AppendLine("<!--");
            sb.AppendLine("  AUTO-GENERATED by EngineContext " + meta.toolVersion
                          + ". Do not edit by hand - regenerate via 'Tools > EngineContext > Generate Context'.");
            sb.AppendLine("  generatedAt: " + meta.generatedAt);
            sb.AppendLine("  schemaVersion: " + meta.schemaVersion
                          + " | scope: " + meta.scope
                          + " | unity: " + meta.unityVersion
                          + " | skippedRefs: " + meta.skippedRefCount);
            if (meta.truncated)
                sb.AppendLine("  summarized: true (some lists were truncated to fit the size budget)");
            sb.AppendLine("-->");
            sb.AppendLine();

            var title = string.IsNullOrEmpty(snapshot.project.productName)
                ? "Unity Project"
                : snapshot.project.productName;
            sb.AppendLine("# Project Context - " + title);
            sb.AppendLine();

            // v0.3 [A-2]: 파일을 열자마자 차별점(코드 밖 배선)이 보이게 하는 한 줄 요약.
            // 카운트는 실제 스캔 결과 그대로 — 0이어도 정직하게 표기한다 (지어내지 않음).
            var eventCount = snapshot.eventBindings.Count;
            var referenceCount = WiredReferencesSection.CountUniqueReferences(snapshot);
            sb.Append("> This snapshot captures " + eventCount + " Inspector-wired event binding(s) and "
                      + referenceCount + " serialized reference field(s) that are invisible in source code - "
                      + "the core reason this file exists. See \"Event Wiring\" and \"Wired References\" below.");
            return sb.ToString();
        }
    }
}
